import React,{useState,useEffect,useRef,useContext,createContext,useMemo,useId} from 'react';
import {createRoot} from 'react-dom/client';
import {AssistantRuntimeProvider,useExternalStoreRuntime,ThreadPrimitive,ComposerPrimitive,MessagePrimitive,ActionBarPrimitive,useAuiState} from '@assistant-ui/react';
import {MarkdownTextPrimitive} from '@assistant-ui/react-markdown';
import remarkGfm from 'remark-gfm';
import {Plus,Search,SlidersHorizontal,FolderPlus,PanelLeft,PanelRight,Paperclip,ArrowUp,Square,Copy,Check,FileText,Download,X,Settings,Archive,Pin,Pencil,Sun,Moon,ChevronDown,Folder,RefreshCw,Power,Activity,ShieldCheck,MessageSquare,ArrowDown,ExternalLink} from 'lucide-react';
import './style.css';
import kLogo from './assets/k-logo.jpg';
import {Usage,UsageDetails} from './usage.jsx';
import './sidebar.css';
import {ProjectSidebar} from './project-sidebar.jsx';
import {workspaceName,sameWorkspace} from './workspace.jsx';
import {moveSessionOrder,searchSessions,sortSessions} from './project-groups.mjs';
import {AppearanceSettings} from './appearance.jsx';
import {applyAppearance,readAppearance,saveAppearance,readTheme,saveTheme} from './appearance.mjs';

const AppContext=createContext(null);
import {ModelPicker,effortName} from './model-picker.jsx';
import './model-picker.css';
const toolStatusName={inProgress:'執行中',running:'執行中',completed:'已完成',failed:'失敗',declined:'已拒絕',cancelled:'已取消',interrupted:'已停止',approved:'已核准',denied:'已拒絕',timedOut:'審查逾時',aborted:'審查中止'};
const statusName={idle:'準備開始',connecting:'正在載入對話…',ready:'已連線',working:'正在工作',stopping:'正在停止背景工作…',completed:'回合完成',interrupted:'已停止',failed:'工作失敗',error:'連線失敗',offline:'後端斷線',uncertain:'工作狀態待確認'};
import {PermissionPicker,permissionModes} from './permission-picker.jsx';
const api=async(route,data)=>{const r=await fetch(`/api/${route}`,data===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json','X-K-Request':'1'},body:JSON.stringify(data)});const v=await r.json();if(!r.ok)throw Error(v.error??'請求失敗');return v;};
const readSidebarPreference=(key,fallback,allowed)=>{try{const value=localStorage.getItem(key);return allowed.includes(value)?value:fallback;}catch{return fallback;}};
const readSidebarOrder=()=>{try{const value=JSON.parse(localStorage.getItem('k-sidebar-manual-order')??'[]');return Array.isArray(value)?value.filter(x=>typeof x==='string'):[];}catch{return[];}};
function IconButton({title,children,...props}){return <button type="button" className="icon-button" title={title} aria-label={title} {...props}>{children}</button>;}
function Modal({title,onClose,children}){const {error}=useContext(AppContext)??{};const ref=useRef(),restoreFocus=useRef(null),headingId=useId();useEffect(()=>{const dialog=ref.current;restoreFocus.current=document.activeElement;if(!dialog.open)dialog.showModal();dialog.querySelector('[data-autofocus]')?.focus();return()=>{if(dialog.open)dialog.close();const target=restoreFocus.current;if(target?.isConnected)target.focus();};},[]);return <dialog ref={ref} aria-labelledby={headingId} onCancel={onClose} onClick={e=>{if(e.target===ref.current)onClose();}}><div className="modal-head"><h2 id={headingId}>{title}</h2><IconButton title="關閉" onClick={onClose}><X size={19}/></IconButton></div>{error&&<p className="model-load-error" role="alert">{error}</p>}{children}</dialog>;}
function CodeHeader({language,code}){const [copied,setCopied]=useState(false);return <div className="code-header"><span>{language||'程式碼'}</span><button onClick={async()=>{await navigator.clipboard.writeText(code);setCopied(true);setTimeout(()=>setCopied(false),1500);}}>{copied?<Check size={14}/>:<Copy size={14}/>} {copied?'已複製':'複製程式碼'}</button></div>;}
function SafeLink({href,children}){const {state,preview}=useContext(AppContext);const normalized=String(href??'').replaceAll('\\','/');const relative=normalized.replace(state.workspace?.replaceAll('\\','/')+'/', '');const artifact=state.artifacts?.find(a=>a===relative);if(artifact)return <button className="inline-file" onClick={()=>preview(artifact)}><FileText size={14}/>{children}</button>;if(!/^https?:\/\//i.test(normalized))return <span>{children}</span>;return <a href={normalized} target="_blank" rel="noreferrer">{children}</a>;}
function Markdown(){return <MarkdownTextPrimitive className="markdown" remarkPlugins={[remarkGfm]} skipHtml smooth={false} components={{CodeHeader,a:SafeLink,img:()=> <span className="muted">外部圖片未自動載入</span>}}/>;}
function UserMessage(){const id=useAuiState(s=>s.message.id);const {state,modelName}=useContext(AppContext);const record=state.messages.find(m=>m.id===id);const files=record?.attachments??[];const change=state.modelChanges?.find(c=>c.turnId===record?.turnId);return <MessagePrimitive.Root className="message user-message">{change&&<div className="model-change-note">主代理已切換：{modelName(change.fromModel)} → {modelName(change.toModel)}</div>}<div className="user-bubble"><MessagePrimitive.Parts/></div>{!!files.length&&<div className="attachment-row">{files.map(a=><a className="file-chip" href={`/api/attachment?id=${a.id}&download=1`} key={a.id}>{a.kind==='image'?<img src={`/api/attachment?id=${a.id}`} alt=""/>:<FileText size={18}/>}<span>{a.name}<small>{Math.ceil(a.size/1024)} KB</small></span></a>)}</div>}</MessagePrimitive.Root>;}
function AssistantMessage(){return <MessagePrimitive.Root className="message assistant-message"><img className="message-mark" src={kLogo} alt="K" width="32" height="32"/><div className="assistant-body"><MessagePrimitive.Parts components={{Text:Markdown}}/><ActionBarPrimitive.Root className="message-actions"><ActionBarPrimitive.Copy asChild><button title="複製回覆"><Copy size={15}/> 複製</button></ActionBarPrimitive.Copy></ActionBarPrimitive.Root></div></MessagePrimitive.Root>;}

function Chat({state,uploads,setUploads,upload,action,effort,setEffort,modelLabel,accessMode,setAccessMode,permissionConfirmed,onChooseModel,blocked}){
 const fileInput=useRef();
 const [steerText,setSteerText]=useState('');
 const runtime=useExternalStoreRuntime({messages:state.messages??[],isRunning:!!state.busy,isDisabled:blocked||!state.threadId||['connecting','offline','error'].includes(state.status),isSendDisabled:uploads.some(a=>a.loading)||state.status==='uncertain',
  convertMessage:m=>({id:m.id,role:m.role,content:[{type:'text',text:m.text}]}),
  onNew:async message=>{const text=message.content.filter(c=>c.type==='text').map(c=>c.text).join('\n');try{const result=await api('send',{text,attachmentIds:uploads.filter(a=>a.id).map(a=>a.id),accessMode,permissionConfirmed,...effort?{effort}:{}});if(!result.sent)throw Error('送出前已停止，訊息留在輸入框。');setUploads([]);}catch(e){if(!runtime.thread.composer.getState().text)runtime.thread.composer.setText(text);action(()=>{throw e;});throw e;}},
  onCancel:()=>action(()=>api('stop',{}))
 });
 useEffect(()=>{if(!state.threadId)return;const key=`k-draft:${state.threadId}`,composer=runtime.thread.composer;const saved=sessionStorage.getItem(key);if(saved)composer.setText(saved);return composer.subscribe(()=>{const text=composer.getState().text;if(text)sessionStorage.setItem(key,text);else sessionStorage.removeItem(key);});},[runtime,state.threadId]);
 return <AssistantRuntimeProvider runtime={runtime}><ThreadPrimitive.Root className="thread" onDragOver={e=>{if(e.dataTransfer.types.includes('Files'))e.preventDefault();}} onDrop={e=>{if(e.dataTransfer.files.length){e.preventDefault();upload([...e.dataTransfer.files]);}}}>
<ThreadPrimitive.Viewport className="viewport"><div className="message-column">{!state.messages?.length&&<div className="empty-state"><img className="big-k" src={kLogo} alt="K 執行中樞" width="96" height="96"/><h1>{state.threadId?'這次要完成什麼工作？':'你的工作，從這裡繼續。'}</h1><p>{state.threadId?'可以拖入檔案、貼上圖片，或直接描述要交付的結果。':'從左側選擇對話，或建立一個新對話。'}</p><div className="starter-grid"><div><FileText/><strong>整理與理解資料</strong><span>文件、表格文字、圖片</span></div><div><Activity/><strong>執行與驗收</strong><span>依工作需要使用工具與協作</span></div><div><ShieldCheck/><strong>保留工作脈絡</strong><span>原對話接續，歷史可回讀</span></div></div></div>}<ThreadPrimitive.Messages components={{UserMessage,AssistantMessage}}/>{state.busy&&<div className="working-indicator"><span/>{state.questions?.length?'等待你的確認':state.progress?.compaction==='compacting'?'正在壓縮工作脈絡…':'主代理正在處理…'}</div>}</div><ThreadPrimitive.ScrollToBottom className="scroll-bottom" aria-label="回到最新訊息"><ArrowDown size={17}/></ThreadPrimitive.ScrollToBottom></ThreadPrimitive.Viewport>
  <div className="composer-area">{state.busy&&<form className="steer-card" onSubmit={e=>{e.preventDefault();const text=steerText.trim();if(!text)return;action(async()=>{await api('steer',{text});setSteerText('');});}}><input aria-label="修正目前工作方向" placeholder="補充或修正目前方向（不重開新回合）" value={steerText} maxLength={32000} onChange={e=>setSteerText(e.target.value)}/><button disabled={!steerText.trim()}>套用修正</button></form>}<ComposerPrimitive.Root className="composer-card"><div className="attachment-row">{uploads.map((a,i)=><div className="file-chip" key={a.id??i}><FileText size={18}/><span>{a.name}<small>{a.loading?'正在讀取…':a.warning??`${Math.ceil(a.size/1024)} KB`}</small></span><IconButton title={`移除附件 ${a.name}`} onClick={()=>setUploads(u=>u.filter(x=>x!==a))}><X size={14}/></IconButton></div>)}</div><ComposerPrimitive.Input className="composer-input" placeholder={state.threadId?'交辦工作，或把檔案拖到這裡…':'請先建立或開啟對話'} aria-label="工作訊息" minRows={2} maxRows={9} submitMode="enter" addAttachmentOnPaste={false} onPaste={e=>{const files=[...e.clipboardData.files];if(files.length){e.preventDefault();upload(files);}}}/><div className="composer-controls"><div className="composer-options"><IconButton title="加入檔案" disabled={!state.threadId||state.busy} onClick={()=>fileInput.current.click()}><Paperclip size={19}/></IconButton><input type="file" ref={fileInput} multiple hidden accept=".txt,.md,.json,.csv,.tsv,.js,.mjs,.ts,.tsx,.jsx,.py,.css,.html,.xml,.yaml,.yml,.log,.pdf,.docx,.png,.jpg,.jpeg,.webp" onChange={e=>{upload([...e.target.files]);e.target.value='';}}/><button type="button" className="composer-model" aria-label="選擇主代理模型" disabled={!state.threadId||blocked||state.busy||state.status==='connecting'} onClick={onChooseModel}>{modelLabel}<ChevronDown size={12}/></button><PermissionPicker value={accessMode} onChange={setAccessMode} disabled={blocked||state.busy||!state.threadId||state.status==='connecting'}/>{accessMode!==(state.accessMode??'workspace-write')&&<small>下次送出套用</small>}<label className="composer-effort"><span className="sr-only">推理程度</span><select aria-label="推理程度" value={effort} onChange={e=>setEffort(e.target.value)} disabled={state.busy}><option value="">沿用設定{state.effort?`（${effortName[state.effort]??state.effort}）`:''}</option>{state.efforts?.map(e=><option key={e} value={e}>{effortName[e]??e}</option>)}</select></label></div>{state.busy?<ComposerPrimitive.Cancel className="send-button" aria-label="停止工作"><Square size={17}/></ComposerPrimitive.Cancel>:<ComposerPrimitive.Send className="send-button" aria-label="送出訊息"><ArrowUp size={21}/></ComposerPrimitive.Send>}</div></ComposerPrimitive.Root><div className="composer-note"><span>{state.workerConnection==='failed'?'Flash 不可用；直接工作與原生 GPT 子代理仍可使用。':'Enter 送出 · Shift + Enter 換行'}</span></div></div>
 </ThreadPrimitive.Root></AssistantRuntimeProvider>;
}

function App(){
 const [appearance,setAppearance]=useState(()=>readAppearance());
 useEffect(()=>{applyAppearance(saveAppearance(appearance));},[appearance]);
 const [state,setState]=useState({messages:[],status:'idle'}),[sessions,setSessions]=useState([]),[projects,setProjects]=useState([]),[online,setOnline]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[archiveMessage,setArchiveMessage]=useState(''),[busy,setBusy]=useState(false),[sidebar,setSidebar]=useState(true),[inspector,setInspector]=useState(true),[panel,setPanel]=useState('artifacts'),[modal,setModal]=useState(null),[models,setModels]=useState([]),[uploads,setUploads]=useState([]),[effort,setEffort]=useState(''),[accessMode,setAccessMode]=useState('workspace-write'),[theme,setTheme]=useState(()=>readTheme()),[sidebarLayout,setSidebarLayout]=useState(()=>readSidebarPreference('k-sidebar-layout','grouped',['grouped','flat'])),[sidebarSort,setSidebarSort]=useState(()=>readSidebarPreference('k-sidebar-sort','recent',['recent','manual'])),[manualOrder,setManualOrder]=useState(()=>readSidebarOrder()),[viewOpen,setViewOpen]=useState(false);
 const workspaceDisplayName=path=>projects.find(project=>sameWorkspace(project.path,path))?.name??workspaceName(path);
 const [permissionConfirmed,setPermissionConfirmed]=useState(false);
 const choosePermission=(mode,confirmed=false)=>{setAccessMode(mode);setPermissionConfirmed(confirmed);};
 const modelName=m=>models.find(x=>x.model===m)?.displayName||(m===state.model?state.modelDisplayName:null)||m||'選擇模型';
 const lock=useRef(false),stateRef=useRef(state),viewRef=useRef(null),viewButtonRef=useRef(null);stateRef.current=state;
 const refresh=async()=>{const [result,registry]=await Promise.all([api('sessions'),api('projects')]);setSessions(result.sessions);setProjects(registry.projects);if(result.unreadable)setNotice(`${result.unreadable} 份舊紀錄無法讀取，已保留原檔。`);};
 const action=async fn=>{if(lock.current)return;lock.current=true;setBusy(true);setError('');try{return await fn();}catch(e){setError(e.message);}finally{lock.current=false;setBusy(false);}};
 useEffect(()=>{const stream=new EventSource('/api/events');stream.onmessage=e=>{setState(JSON.parse(e.data));setOnline(true);};stream.onerror=()=>{setOnline(false);};refresh().catch(e=>setError(e.message));return()=>stream.close();},[]);
 useEffect(()=>{
  // Only floating action menus dismiss. Tool/approval disclosure records
  // deliberately stay expanded while the user reads other parts of a job.
  const openMenus=()=>[...document.querySelectorAll('details.session-menu[open]')];
  const outside=e=>{for(const menu of openMenus())if(!menu.contains(e.target))menu.open=false;};
  const escape=e=>{if(e.key!=='Escape')return;for(const menu of openMenus()){const focused=menu.contains(document.activeElement);menu.open=false;if(focused)menu.querySelector('summary')?.focus();}};
  const chosen=e=>{const button=e.target.closest?.('details.session-menu button');if(button)button.closest('details').open=false;};
  const exclusive=e=>{if(e.target.matches?.('details.session-menu[open]'))for(const menu of openMenus())if(menu!==e.target)menu.open=false;};
  document.addEventListener('pointerdown',outside);document.addEventListener('focusin',outside);document.addEventListener('keydown',escape);document.addEventListener('click',chosen);document.addEventListener('toggle',exclusive,true);
  return()=>{document.removeEventListener('pointerdown',outside);document.removeEventListener('focusin',outside);document.removeEventListener('keydown',escape);document.removeEventListener('click',chosen);document.removeEventListener('toggle',exclusive,true);};
 },[]);
 useEffect(()=>{refresh().catch(e=>setError(e.message));},[state.threadId,state.title,state.model,state.status==='ready']);
 useEffect(()=>{setUploads([]);setEffort('');setNotice('');setAccessMode(state.accessMode??'workspace-write');setPermissionConfirmed(false);},[state.threadId]);
 useEffect(()=>{if(state.busy)setNotice('');},[state.busy]);
 useEffect(()=>{document.documentElement.dataset.theme=saveTheme(theme);},[theme]);
 useEffect(()=>{try{localStorage.setItem('k-sidebar-layout',sidebarLayout);localStorage.setItem('k-sidebar-sort',sidebarSort);}catch{}},[sidebarLayout,sidebarSort]);
 useEffect(()=>{try{localStorage.setItem('k-sidebar-manual-order',JSON.stringify(manualOrder));}catch{}},[manualOrder]);
 useEffect(()=>{const outside=e=>{if(viewRef.current&&!viewRef.current.contains(e.target))setViewOpen(false);};const escape=e=>{if(e.key==='Escape'&&viewOpen){setViewOpen(false);viewButtonRef.current?.focus();}};document.addEventListener('pointerdown',outside);document.addEventListener('keydown',escape);return()=>{document.removeEventListener('pointerdown',outside);document.removeEventListener('keydown',escape);};},[viewOpen]);
 useEffect(()=>{if(state.questions?.length){setInspector(true);setPanel('approvals');}},[state.questions?.length]);
 const upload=async files=>{
  if(!state.threadId||state.busy){setError('請先開啟對話，並等待目前回合結束後加入附件。');return;}
  if(uploads.length+files.length>8){setError('每則訊息最多 8 份附件。');return;}
  const threadId=state.threadId;
  for(const file of files){if(file.size>8*1024*1024){setError(`${file.name} 超過 8 MB。`);continue;}const pending={name:file.name,loading:true};setUploads(u=>[...u,pending]);try{const base64=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=reject;reader.readAsDataURL(file);});const saved=await api('upload',{threadId,name:file.name,base64});if(stateRef.current.threadId===threadId)setUploads(u=>u.map(a=>a===pending?saved:a));}catch(e){setUploads(u=>u.filter(a=>a!==pending));setError(e.message);}}
 };
 const open=async(s)=>{if(s.threadId===state.threadId&&s.model===state.model&&state.status==='ready'&&state.workerConnection!=='failed')return true;if(uploads.length&&!confirm('切換對話會移除尚未送出的附件選取；原上傳檔案保留。要繼續嗎？'))return false;return await action(()=>api('open',s));};
 const metadata=async data=>{await api('metadata',data);await refresh();};
 const projectMetadata=async data=>{await api('projects/metadata',data);await refresh();};
 const preview=async name=>{setModal({type:'preview',name,loading:true});try{const r=await fetch(`/api/artifact?path=${encodeURIComponent(name)}`);if(!r.ok){const e=await r.json();throw Error(e.error);}if(r.headers.get('content-type')?.startsWith('image/'))setModal({type:'preview',name,image:true});else setModal({type:'preview',...await r.json(),name});}catch(e){setModal(null);setError(e.message);}};
 const createInProject=path=>setModal({type:'new',path:path??state.workspace});
 const createConversation=selection=>action(async()=>{if(uploads.length&&!confirm('建立新對話會清除尚未送出的附件選取；原上傳檔案保留。要繼續嗎？'))return;if(!sameWorkspace(modal.path,state.workspace))await api('workspace',{path:modal.path});await api('open',selection);setModal(null);await refresh();});
 const addWorkspace=()=>action(async()=>{const selected=await api('pick-workspace',{path:state.workspace});if(selected.cancelled)return;if(!selected.path)throw Error('工作區選擇器沒有回傳資料夾。');await api('projects',{path:selected.path});await refresh();setNotice(`已加入工作區：${workspaceName(selected.path)}`);});
 const openListed=async session=>{const result=await open({model:session.model,threadId:session.threadId});if(result!==false&&result!==undefined)setModal(null);};
 const restoreArchived=session=>action(async()=>{await metadata({threadId:session.threadId,archived:false});setArchiveMessage(`已將「${session.title||'未命名對話'}」移回「${workspaceDisplayName(session.workspace)}」`);});
 const restoreArchivedProject=project=>action(async()=>{await projectMetadata({path:project.path,archived:false});setArchiveMessage(`已還原工作區「${project.name}」；其中已封存的對話仍保留在對話封存清單。`);});
 const archiveRows=sortSessions(sessions.filter(s=>!s.parentThreadId&&s.archived));
 const archivedProjectRows=projects.filter(project=>project.archived);
 const archiveCount=archiveRows.length+archivedProjectRows.length;
 const searchRows=modal?.type==='search'?searchSessions(projects,sessions,modal.query):[];
 const dateUsed=session=>session.lastOpenedAt&&Number.isFinite(Date.parse(session.lastOpenedAt))?new Date(session.lastOpenedAt).toLocaleDateString('zh-TW',{year:'numeric',month:'numeric',day:'numeric'}):'日期未知';
 const moveConversation=(session,list,direction)=>setManualOrder(order=>moveSessionOrder(order,sessions.filter(s=>!s.parentThreadId&&!s.archived),list,session.threadId,direction));
 const chooseView=(setter,value)=>{setter(value);setViewOpen(false);viewButtonRef.current?.focus();};
 const disabled=busy||state.busy||state.status==='connecting'||!online;
 return <AppContext.Provider value={{state,preview,modelName,error}}><div className={`app ${sidebar?'':'sidebar-hidden'} ${inspector?'':'inspector-hidden'}`}>
  <aside className="sidebar">
   <div className="brand"><img className="brand-icon" src={kLogo} alt="" width="40" height="40"/><div>K 執行中樞<small>通用工作台</small></div><IconButton title="收合側欄" onClick={()=>setSidebar(false)}><PanelLeft size={17}/></IconButton></div>
   <div className="sidebar-toolbar">
    <button className="new-chat" onClick={()=>createInProject()} disabled={disabled}><Plus size={19}/> 新對話</button>
   </div>
   <div className="workspace-tools">
   <div className="workspace-heading"><span>工作區</span>
     <IconButton title="搜尋對話" onClick={()=>setModal({type:'search',query:''})}><Search size={16}/></IconButton>
     <div className="view-control" ref={viewRef}>
      <IconButton title="檢視選項" aria-haspopup="true" aria-expanded={viewOpen} ref={viewButtonRef} onClick={()=>setViewOpen(value=>!value)}><SlidersHorizontal size={16}/></IconButton>
      {viewOpen&&<div className="sidebar-view-popover" aria-label="檢視選項">
       <strong>分組方式</strong>
       <button aria-pressed={sidebarLayout==='grouped'} onClick={()=>chooseView(setSidebarLayout,'grouped')}>{sidebarLayout==='grouped'&&<Check size={14}/>}依工作區</button>
       <button aria-pressed={sidebarLayout==='flat'} onClick={()=>chooseView(setSidebarLayout,'flat')}>{sidebarLayout==='flat'&&<Check size={14}/>}單一清單</button>
       <span className="view-divider"/><strong>排序方式</strong>
       <button aria-pressed={sidebarSort==='recent'} onClick={()=>chooseView(setSidebarSort,'recent')}>{sidebarSort==='recent'&&<Check size={14}/>}最近使用</button>
       <button aria-pressed={sidebarSort==='manual'} onClick={()=>chooseView(setSidebarSort,'manual')}>{sidebarSort==='manual'&&<Check size={14}/>}手動排序</button>
       {sidebarSort==='manual'&&<small>在對話選單中使用「上移／下移對話」調整順序。</small>}
      </div>}
     </div>
     <IconButton title="新增工作區" disabled={disabled} onClick={addWorkspace}><FolderPlus size={17}/></IconButton>
     <IconButton title="已封存" onClick={()=>{setArchiveMessage('');setModal({type:'archive'});}}><Archive size={16}/>{archiveCount>0&&<small className="archive-count">{archiveCount}</small>}</IconButton>
    </div>
   </div>
   <ProjectSidebar {...{projects,sessions,state,disabled,modelName,order:manualOrder}} layout={sidebarLayout} sort={sidebarSort} onOpen={open} onCreate={createInProject} onRename={session=>setModal({type:'rename',session})} onMetadata={data=>action(()=>metadata(data))} onMove={moveConversation} onRenameProject={project=>setModal({type:'rename-project',project})} onProjectMetadata={data=>action(()=>projectMetadata(data))}/>
   <div className="sidebar-bottom"><Usage state={state} online={online} onDetails={()=>setModal({type:'usage'})}/><button title="設定與工作環境" onClick={()=>setModal({type:'settings'})}><Settings size={16}/> 設定</button></div>
  </aside>
  <main><header><div className="header-title">{!sidebar&&<IconButton title="展開側欄" onClick={()=>setSidebar(true)}><PanelLeft size={18}/></IconButton>}<div><h1>{state.title||workspaceDisplayName(state.workspace)}</h1><span title={state.workspace}>{state.threadId?`${workspaceDisplayName(state.workspace)} · ${modelName(state.model)}`:'通用工作台'}</span></div></div><div className="header-actions"><span className={`status ${!online?'offline':state.busy?'running':'connected'}`} title={online?'本機後端已連線':'本機後端連線中斷'} aria-label={`${online?'本機後端已連線':'本機後端連線中斷'} · ${online?(statusName[state.status]??state.status):'連線中斷'}`} role="status"><i/>{online?(statusName[state.status]??state.status):'連線中斷'}</span><IconButton title="切換工具與成果面板" onClick={()=>setInspector(v=>!v)}><PanelRight size={19}/></IconButton></div></header>
  {(error||state.error||!online)&&<div className="alert" role="alert"><span>{error||state.error||'介面暫時斷線。原工作不會重送；請等待連線或重開啟動器。'}</span><IconButton title="關閉提示" onClick={()=>setError('')}><X size={15}/></IconButton></div>}{notice&&<div className="notice">{notice}<button onClick={()=>setNotice('')}>知道了</button></div>}
  {state.workerConnection==='connecting'&&<div className="notice" role="status">Flash 工人準備中；不依賴 Flash 的主腦工作可直接送出。</div>}
  {state.workerConnection==='failed'&&<div className="notice" role="status">{state.workerError} 直接工作與原生 GPT 子代理不受影響。<button onClick={()=>open({threadId:state.threadId,model:state.model})}>重新連線</button></div>}
  <Chat key={state.threadId||'empty'} blocked={busy||!online} onChooseModel={()=>setModal({type:'model',threadId:state.threadId})} modelLabel={modelName(state.model)} {...{state,uploads,setUploads,upload,action,effort,setEffort,accessMode,permissionConfirmed}} setAccessMode={choosePermission}/>
  </main>
  <aside className="inspector"><div className="inspector-head"><strong>工作面板</strong><IconButton title="重新查詢工人" disabled={!state.threadId||busy} onClick={()=>action(()=>api('workers',{}))}><RefreshCw size={16}/></IconButton></div><div className="panel-tabs">{[['artifacts','成果'],['progress','進度'],['activity','活動'],['approvals','核准']].map(([id,label])=><button key={id} className={panel===id?'active':''} onClick={()=>setPanel(id)}>{label}{id==='approvals'&&!!state.questions?.length&&<b>{state.questions.length}</b>}</button>)}</div><div className="panel-body">
  {panel==='artifacts'&&<><p className="panel-explanation">直接查看主代理或子代理交付的檔案。檔案存在不代表已通過主代理驗收。</p>{state.artifacts?.map(name=><div className="artifact-card" key={name}><FileText size={22}/><div><strong>{name.split('/').at(-1)}</strong><small>{name}</small><div className="artifact-actions"><button onClick={()=>preview(name)}>預覽</button><a href={`/api/artifact?path=${encodeURIComponent(name)}&download=1`}><Download size={13}/>下載</a></div></div></div>)}{!state.artifacts?.length&&<div className="panel-empty"><Folder/><p>成果會出現在這裡</p><small>完成工作後自動查詢，也可按右上角更新。</small></div>}{state.workers?.map(w=><div className="worker-card" key={w.requestId}><span>{w.requestId}</span><strong>{({completed:'工人已結束',cancelled:'已取消',running:'執行中',failed:'失敗',unresolved:'狀態未確認，不要重派',unavailable:'無法查明'})[w.status]??w.status}</strong></div>)}</>}
  {panel==='activity'&&<>{state.tools?.map(t=><details className="tool-card" key={t.id}><summary><Activity size={14}/><span>{t.name}</span><small>{toolStatusName[t.status]??t.status}</small></summary>{t.details&&<pre>{typeof t.details==='string'?t.details:JSON.stringify(t.details,null,2)}</pre>}{t.output&&<pre>{t.output}</pre>}</details>)}{!state.tools?.length&&<div className="panel-empty"><Activity/><p>尚無工具活動</p><small>這裡顯示真正執行的工具，不是模型的計畫文字。</small></div>}</>}
  {panel==='progress'&&<ProgressPanel state={state} action={action}/>}
  {panel==='approvals'&&<>{state.questions?.map(q=><Approval key={q.id} question={q} action={action}/>)}{!state.questions?.length&&<div className="panel-empty"><ShieldCheck/><p>沒有等待中的核准</p><small>{state.accessMode==='auto-review'?'需要額外存取時由 Codex 自動審查；審查結果顯示在活動。':state.accessMode==='danger-full-access'?'完整存取已啟用；一般檔案與網路操作不再逐項核准。':'每次只核准顯示的操作，不會自動放行後續要求。'}</small></div>}</>}
  </div><div className="panel-footer"><ShieldCheck size={14}/>{(permissionModes[state.accessMode??'workspace-write']).name} · {(permissionModes[state.accessMode??'workspace-write']).summary}</div></aside>
  {modal?.type==='usage'&&<Modal title="額度與用量" onClose={()=>setModal(null)}><UsageDetails state={state} online={online}/><div className="modal-actions"><button onClick={()=>setModal(null)}>完成</button></div></Modal>}
  {modal?.type==='new'&&<Modal title="新對話" onClose={()=>setModal(null)}><label className="setting-row"><span>工作區</span><select aria-label="新對話工作區" value={modal.path??state.workspace} onChange={e=>setModal(m=>({...m,path:e.target.value}))}>{projects.map(p=><option key={p.path} value={p.path}>{p.name}</option>)}</select></label><ModelPicker currentModel={state.model} currentWorkerModel={state.workerPolicy?.model} disabled={disabled} loadModels={()=>api('models')} onCatalog={setModels} onClose={()=>setModal(null)} onCreate={createConversation}/></Modal>}
  {modal?.type==='search'&&<Modal title="搜尋對話" onClose={()=>setModal(null)}><p className="modal-description">搜尋對話標題、工作區與模型名稱；不搜尋訊息內文。已封存的對話也會列出。</p><label className="sidebar-dialog-search"><Search size={16}/><input data-autofocus autoFocus aria-label="搜尋標題、工作區或模型" placeholder="輸入標題、工作區或模型" value={modal.query} onChange={e=>setModal(m=>({...m,query:e.target.value}))}/><IconButton title="清除搜尋" disabled={!modal.query} onClick={()=>setModal(m=>({...m,query:''}))}><X size={14}/></IconButton></label><div className="dialog-session-list search-results">{searchRows.map(s=><button className="search-result" key={s.threadId} disabled={disabled} onClick={()=>openListed(s)}><span className="result-title"><strong>{s.title||'未命名對話'}</strong>{s.archived&&<em>已封存</em>}</span><small>{workspaceDisplayName(s.workspace)} · {modelName(s.model)}</small><time>{dateUsed(s)}</time></button>)}{modal.query.trim()&&!searchRows.length&&<p className="dialog-list-empty">沒有符合條件的對話。</p>}{!modal.query.trim()&&<p className="dialog-list-empty">輸入標題、工作區或模型名稱開始搜尋。</p>}</div><div className="modal-actions"><button onClick={()=>setModal(null)}>關閉</button></div></Modal>}
  {modal?.type==='archive'&&<Modal title="已封存" onClose={()=>setModal(null)}>{archiveMessage&&<p className="archive-status" role="status" aria-live="polite">{archiveMessage}</p>}{!!archivedProjectRows.length&&<section className="archive-section"><h3 className="archive-section-title">工作區</h3><p className="modal-description">還原工作區會讓其中未封存的對話回到側欄；已封存對話仍留在對話封存清單。</p><div className="dialog-session-list archive-results">{archivedProjectRows.map(project=><div className="archive-result" key={project.path}><div className="archive-open archive-project-label"><strong title={project.name}>{project.name}</strong><span title={project.path}>{project.path}</span></div><button className="restore-session" disabled={disabled} onClick={()=>restoreArchivedProject(project)}>還原工作區</button></div>)}</div></section>}<section className="archive-section"><h3 className="archive-section-title">對話</h3><div className="dialog-session-list archive-results">{archiveRows.map(s=><div className="archive-result" key={s.threadId}><button className="archive-open" disabled={disabled} onClick={()=>openListed(s)}><strong title={s.title||'未命名對話'}>{s.title||'未命名對話'}</strong><span>{workspaceDisplayName(s.workspace)}</span><time>最近使用：{dateUsed(s)}</time></button><button className="restore-session" disabled={disabled} onClick={()=>restoreArchived(s)}>移回清單</button></div>)}{!archiveRows.length&&<p className="dialog-list-empty">目前沒有已封存的對話。</p>}</div></section>{!archiveCount&&<p className="dialog-list-empty">目前沒有已封存的工作區或對話。</p>}<div className="modal-actions"><button onClick={()=>setModal(null)}>關閉</button></div></Modal>}
  {modal?.type==='model'&&<Modal title="切換主代理模型" onClose={()=>setModal(null)}><ModelPicker mode="switch" currentModel={state.model} currentEffort={state.effort} hasHistory={state.messages?.some(m=>m.role==='user')} disabled={disabled} loadModels={()=>api('models')} onCatalog={setModels} onClose={()=>setModal(null)} onCreate={selection=>action(async()=>{const result=await api('model',{threadId:modal.threadId,...selection});setEffort('');setModal(null);setNotice(`已選擇 ${modelName(result.model)}，下一則訊息套用。`);await refresh();})}/></Modal>}
  {modal?.type==='rename'&&<Rename key={modal.session.threadId} title="重新命名工作" value={modal.session.title} label="工作名稱" onClose={()=>setModal(null)} onSave={title=>action(async()=>{await metadata({threadId:modal.session.threadId,title});setModal(null);})}/>}
  {modal?.type==='rename-project'&&<Rename key={modal.project.path} title="重新命名工作區" value={modal.project.name} label="工作區顯示名稱" onClose={()=>setModal(null)} onSave={name=>action(async()=>{await projectMetadata({path:modal.project.path,name});setModal(null);})}/>}
  {modal?.type==='preview'&&<Modal title={modal.name.split('/').at(-1)} onClose={()=>setModal(null)}>{modal.loading?<p>載入成果…</p>:modal.image?<img className="preview-image" src={`/api/artifact?path=${encodeURIComponent(modal.name)}`} alt={modal.name}/>:modal.isText?<pre className="file-preview">{modal.text}</pre>:<p>此格式請下載後以本機應用程式開啟。</p>}{modal.truncated&&<p>預覽僅顯示前 256 KiB，下載保留完整內容。</p>}<div className="modal-actions"><a className="primary" href={`/api/artifact?path=${encodeURIComponent(modal.name)}&download=1`}><Download size={15}/>下載完整檔案</a></div></Modal>}
  {modal?.type==='settings'&&<Modal title="設定與工作環境" onClose={()=>setModal(null)}><div className="setting-row"><span>介面外觀</span><div><button className={theme==='light'?'chosen':''} aria-pressed={theme==='light'} onClick={()=>setTheme('light')}><Sun size={16}/>淺色</button><button className={theme==='warm'?'chosen':''} aria-pressed={theme==='warm'} onClick={()=>setTheme('warm')}><Sun size={16}/>暖色</button><button className={theme==='dark'?'chosen':''} aria-pressed={theme==='dark'} onClick={()=>setTheme('dark')}><Moon size={16}/>深色</button></div></div><AppearanceSettings value={appearance} onChange={setAppearance}/><div className="setting-row"><span>目前工作區資料夾</span><div><code>{state.workspace??'D:\\K-harness'}</code><button disabled={disabled} onClick={addWorkspace}>新增工作區</button></div></div><p className="modal-description">附件支援 UTF-8 文字、程式碼、CSV、PDF、DOCX 與圖片；每檔最高 8 MB。PDF／DOCX 先擷取文字，掃描 PDF 請改傳頁面圖片。</p><p className="modal-description">關閉視窗不會停止背景工作。需要完全結束 K，請使用下面的停止後端。</p><div className="modal-actions"><button className="danger" onClick={()=>{if(confirm('停止 K 後端與可確認的執行中工作？已寫成果保留。'))action(async()=>{await api('shutdown',{});setModal(null);setOnline(false);});}}><Power size={15}/>停止後端</button><button className="primary" onClick={()=>setModal(null)}>完成</button></div></Modal>}
 </div></AppContext.Provider>;
}
function Rename({title,value,label,onClose,onSave}){const [name,setName]=useState(value??'');return <Modal title={title} onClose={onClose}><form onSubmit={e=>{e.preventDefault();onSave(name.trim());}}><input autoFocus className="text-field" aria-label={label} maxLength={120} value={name} onChange={e=>setName(e.target.value)}/><div className="modal-actions"><button type="button" onClick={onClose}>取消</button><button className="primary" disabled={!name.trim()}>儲存</button></div></form></Modal>;}
function Approval({question:q,action}){const [answers,setAnswers]=useState({});return <div className="approval-card"><div className="approval-title"><ShieldCheck size={19}/>{q.kind==='approval'?(q.title??'需要操作核准'):'需要你的回答'}{q.isSubagent&&<span className="approval-scope">子代理</span>}</div>{q.kind==='approval'?<><p>{q.text}</p><details open><summary>實際請求內容</summary><pre>{JSON.stringify(q.details,null,2)}</pre></details><div className="approval-buttons"><button onClick={()=>action(()=>api('answer',{id:q.id,accept:false}))}>拒絕</button><button className="primary" disabled={q.canAccept===false} onClick={()=>action(()=>api('answer',{id:q.id,accept:true}))}>{q.canAccept===false?'目前無法核准':(q.acceptLabel??'只核准這一次')}</button></div></>:<form onSubmit={e=>{e.preventDefault();action(()=>api('answer',{id:q.id,answers:Object.fromEntries(q.questions.map(x=>[x.id,answers[x.id]??'']))}));}}>{q.questions.map(x=><label key={x.id}>{x.question}{x.options?.length?<select value={answers[x.id]??''} onChange={e=>setAnswers(a=>({...a,[x.id]:e.target.value}))}><option value="">請選擇</option>{x.options.map(o=><option key={o.label} value={o.label}>{o.label}</option>)}</select>:<input value={answers[x.id]??''} onChange={e=>setAnswers(a=>({...a,[x.id]:e.target.value}))}/>}</label>)}<button className="primary">送出回答</button></form>}</div>;}
function ProgressPanel({state,action}){const [objective,setObjective]=useState(state.goal?.objective??'');useEffect(()=>setObjective(state.goal?.objective??''),[state.goal?.objective]);const usage=state.progress?.tokenUsage;return <div className="progress-panel"><form className="goal-card" onSubmit={e=>{e.preventDefault();action(()=>api('goal',{objective}));}}><strong>目前目標</strong><textarea aria-label="目前目標" maxLength={4000} placeholder="設定長程工作要持續完成的結果" value={objective} onChange={e=>setObjective(e.target.value)}/><div className="progress-actions"><button disabled={!objective.trim()}>儲存目標</button>{state.goal&&<button type="button" onClick={()=>action(()=>api('goal',{clear:true}))}>清除</button>}</div>{state.goal&&<small>狀態：{state.goal.status} · 已用 {state.goal.tokensUsed??0} tokens</small>}</form>{!!state.progress?.plan?.length&&<section className="plan-card"><strong>主代理計畫</strong>{state.progress.explanation&&<p>{state.progress.explanation}</p>}<ol>{state.progress.plan.map((step,i)=><li key={`${i}-${step.step}`} data-status={step.status}>{step.step}<small>{step.status}</small></li>)}</ol></section>}<section className="context-card"><strong>工作脈絡</strong><p>壓縮狀態：{state.progress?.compaction??'idle'}{state.progress?.compactions?` · 已完成 ${state.progress.compactions} 次`:''}</p>{usage&&<p>目前脈絡：{usage.total?.totalTokens??0}{usage.modelContextWindow?` / ${usage.modelContextWindow}`:''} tokens</p>}<button disabled={state.busy||!state.threadId} onClick={()=>action(()=>api('compact',{}))}>現在壓縮</button></section></div>;}

class ErrorBoundary extends React.Component{state={error:null};static getDerivedStateFromError(error){return {error};}render(){if(this.state.error)return <div className="fatal"><h1>K 介面載入失敗</h1><p>原工作未重新送出，後端可能仍在執行。</p><pre>{this.state.error.message}</pre><button onClick={()=>location.reload()}>重新載入介面</button></div>;return this.props.children;}}
createRoot(document.getElementById('root')).render(<ErrorBoundary><App/></ErrorBoundary>);
